---
title: "README"
output: html_document
---

# Spotify Me
[link here!](https://kchiu17.shinyapps.io/scripts/)

##What is Spotify Me?
What we have created is an interactive visualization that allows the user to better understand 
important trends that occur within the songs of different artists that are on Spotify. 

##How Do You Use It?
Firstly, the user would specify which artists songs that they want to specifically review and 
understand better. Once given a specific artist, the user can then filter the music down to their 
desired preference of release date, tempo, danceability, and duration of the song. Once the user
has finished setting their preferences to filter the data set down, they can then choose what kind
of interaction they want to explore within the music. They have the freedom of changing which
element of the songs will be shown on both the X and Y axes. This will allow them to be able to 
fully explore and understand their music. The elements that they can select for the music are tempo,
album release date, danceability, instrumentalness, and duration of the song. Not only are the users
given full freedom to mix and match these elements, but the popularity of each of the songs are also
indicated by the size of each point representing the song. The larger the point is the more popular 
that particular song. If the user has found a song that they wanted to explore more about in the 
future then they can simply hover over the song and it will give them the name of the song so they
can look it up for themselves as well as the exact measurement of the X and Y axis elements of the
song. The graph will always continue to adapt as the user switches around the filters, the elements,
and even the artist selection!

##Who Is This For?
For this project we thought of three different user groups that we believed could make the best use
of our visualization.
* **Dancers:** Our design was highly catered towards making sure that dancers would be able to find 
music to dance to as easily as possible. Through setting their preferences for the tempo of the
songs, the danceability, and duration of the songs, a dancer could best find music that can cater
to their dance routine. Not only this, but they would be able to evaluate which songs were the most
popular so that they would be able to know what songs are most familiar for the general public. 
* **DJ's:** We also catered our project towards people who are possibly interested in 
producing, mixing, or DJ-ing music for the general public or clients. We thought that being able to
select the danceability, tempo, and duration of songs would be especially helpful for DJ's because
they would be able to cater their playlists for whatever venue that they needed to play at. This 
would also allow them to more easily change the music that they played on the spot to find music
that better fit the environment or constraints of their crowd. Knowing the popularity of the music
would also be a large help so that they could simply choose whatever is popular without having to 
worry too much about whether some music was not likable. 
* **Musical Producers:** We also wanted to help out musical producers as well with our project. We 
hoped that people who were interested in creating certain types of music would be able to more 
easily understand the trends of different styles of music as well as understand how different
elements of music interacted when it came to artists that were most influential to them that they
may want to mimic. We also believed that having the popularity be shown on every graph would help
the producers understand what elements of the music tended to be well received to the general 
audience on Spotify. We believe that being able to better understand music wholistically in this
way as well as allowing producers the freedom to compare as they like would ultimately help them
make better music.

##What Can This Do For You?
Beyond these more specific groups of individuals, we believe that this could also help the general 
user of Spotify be able to find music that they enjoy. Being able to find songs to fit their current
mood, or fit into a specific playlist can be a struggle for any person who uses spotify, and this
could ultimately make that a much simpler task. And even above this, being able to see cool 
visualizations of songs from artists that you actually care about is just plain fun!


